package ml.karmaconfigs.api.bukkit.soundutil;

import com.google.common.base.Enums;
import com.google.common.cache.Cache;
import com.google.common.cache.CacheBuilder;

import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.util.regex.Pattern;

/**
 * Private GSA code
 * <p>
 * The use of this code
 * without GSA team authorization
 * will be a violation of
 * terms of use determined
 * in <a href="https://karmaconfigs.github.io/page/license"> here </a>
 */
public enum Sound {
    /** Bukkit sound name */ AMBIENT_CAVE("AMBIENCE_CAVE"),
    /** Bukkit sound name */ AMBIENT_UNDERWATER_ENTER,
    /** Bukkit sound name */ AMBIENT_UNDERWATER_EXIT,
    /** Bukkit sound name */ AMBIENT_UNDERWATER_LOOP("AMBIENT_UNDERWATER_EXIT"),
    /** Bukkit sound name */ AMBIENT_UNDERWATER_LOOP_ADDITIONS("AMBIENT_UNDERWATER_EXIT"),
    /** Bukkit sound name */ AMBIENT_UNDERWATER_LOOP_ADDITIONS_RARE("AMBIENT_UNDERWATER_EXIT"),
    /** Bukkit sound name */ AMBIENT_UNDERWATER_LOOP_ADDITIONS_ULTRA_RARE("AMBIENT_UNDERWATER_EXIT"),
    /** Bukkit sound name */ BLOCK_ANVIL_BREAK("ANVIL_BREAK"),
    /** Bukkit sound name */ BLOCK_ANVIL_DESTROY,
    /** Bukkit sound name */ BLOCK_ANVIL_FALL,
    /** Bukkit sound name */ BLOCK_ANVIL_HIT("BLOCK_ANVIL_FALL"),
    /** Bukkit sound name */ BLOCK_ANVIL_LAND("ANVIL_LAND"),
    /** Bukkit sound name */ BLOCK_ANVIL_PLACE("BLOCK_ANVIL_FALL"),
    /** Bukkit sound name */ BLOCK_ANVIL_STEP("BLOCK_ANVIL_FALL"),
    /** Bukkit sound name */ BLOCK_ANVIL_USE("ANVIL_USE"),
    /** Bukkit sound name */ BLOCK_BAMBOO_BREAK,
    /** Bukkit sound name */ BLOCK_BAMBOO_FALL,
    /** Bukkit sound name */ BLOCK_BAMBOO_HIT,
    /** Bukkit sound name */ BLOCK_BAMBOO_PLACE,
    /** Bukkit sound name */ BLOCK_BAMBOO_SAPLING_BREAK,
    /** Bukkit sound name */ BLOCK_BAMBOO_SAPLING_HIT,
    /** Bukkit sound name */ BLOCK_BAMBOO_SAPLING_PLACE,
    /** Bukkit sound name */ BLOCK_BAMBOO_STEP,
    /** Bukkit sound name */ BLOCK_BARREL_CLOSE,
    /** Bukkit sound name */ BLOCK_BARREL_OPEN,
    /** Bukkit sound name */ BLOCK_BEACON_ACTIVATE,
    /** Bukkit sound name */ BLOCK_BEACON_AMBIENT,
    /** Bukkit sound name */ BLOCK_BEACON_DEACTIVATE("BLOCK_BEACON_AMBIENT"),
    /** Bukkit sound name */ BLOCK_BEACON_POWER_SELECT("BLOCK_BEACON_AMBIENT"),
    /** Bukkit sound name */ BLOCK_BEEHIVE_DRIP,
    /** Bukkit sound name */ BLOCK_BEEHIVE_ENTER,
    /** Bukkit sound name */ BLOCK_BEEHIVE_EXIT,
    /** Bukkit sound name */ BLOCK_BEEHIVE_SHEAR,
    /** Bukkit sound name */ BLOCK_BEEHIVE_WORK,
    /** Bukkit sound name */ BLOCK_BELL_RESONATE,
    /** Bukkit sound name */ BLOCK_BELL_USE,
    /** Bukkit sound name */ BLOCK_BLASTFURNACE_FIRE_CRACKLE,
    /** Bukkit sound name */ BLOCK_BREWING_STAND_BREW,
    /** Bukkit sound name */ BLOCK_BUBBLE_COLUMN_BUBBLE_POP,
    /** Bukkit sound name */ BLOCK_BUBBLE_COLUMN_UPWARDS_AMBIENT,
    /** Bukkit sound name */ BLOCK_BUBBLE_COLUMN_UPWARDS_INSIDE,
    /** Bukkit sound name */ BLOCK_BUBBLE_COLUMN_WHIRLPOOL_AMBIENT,
    /** Bukkit sound name */ BLOCK_BUBBLE_COLUMN_WHIRLPOOL_INSIDE,
    /** Bukkit sound name */ BLOCK_CAMPFIRE_CRACKLE,
    /** Bukkit sound name */ BLOCK_CHEST_CLOSE("CHEST_CLOSE", "ENTITY_CHEST_CLOSE"),
    /** Bukkit sound name */ BLOCK_CHEST_LOCKED,
    /** Bukkit sound name */ BLOCK_CHEST_OPEN("CHEST_OPEN", "ENTITY_CHEST_OPEN"),
    /** Bukkit sound name */ BLOCK_CHORUS_FLOWER_DEATH,
    /** Bukkit sound name */ BLOCK_CHORUS_FLOWER_GROW,
    /** Bukkit sound name */ BLOCK_COMPARATOR_CLICK,
    /** Bukkit sound name */ BLOCK_COMPOSTER_EMPTY,
    /** Bukkit sound name */ BLOCK_COMPOSTER_FILL,
    /** Bukkit sound name */ BLOCK_COMPOSTER_FILL_SUCCESS,
    /** Bukkit sound name */ BLOCK_COMPOSTER_READY,
    /** Bukkit sound name */ BLOCK_CONDUIT_ACTIVATE,
    /** Bukkit sound name */ BLOCK_CONDUIT_AMBIENT,
    /** Bukkit sound name */ BLOCK_CONDUIT_AMBIENT_SHORT,
    /** Bukkit sound name */ BLOCK_CONDUIT_ATTACK_TARGET,
    /** Bukkit sound name */ BLOCK_CONDUIT_DEACTIVATE,
    /** Bukkit sound name */ BLOCK_CORAL_BLOCK_BREAK,
    /** Bukkit sound name */ BLOCK_CORAL_BLOCK_FALL,
    /** Bukkit sound name */ BLOCK_CORAL_BLOCK_HIT,
    /** Bukkit sound name */ BLOCK_CORAL_BLOCK_PLACE,
    /** Bukkit sound name */ BLOCK_CORAL_BLOCK_STEP,
    /** Bukkit sound name */ BLOCK_CROP_BREAK,
    /** Bukkit sound name */ BLOCK_DISPENSER_DISPENSE,
    /** Bukkit sound name */  BLOCK_DISPENSER_FAIL,
    /** Bukkit sound name */ BLOCK_DISPENSER_LAUNCH,
    /** Bukkit sound name */ BLOCK_ENCHANTMENT_TABLE_USE,
    /** Bukkit sound name */ BLOCK_ENDER_CHEST_CLOSE,
    /** Bukkit sound name */  BLOCK_ENDER_CHEST_OPEN,
    /** Bukkit sound name */ BLOCK_END_GATEWAY_SPAWN,
    /** Bukkit sound name */ BLOCK_END_PORTAL_FRAME_FILL,
    /** Bukkit sound name */ BLOCK_END_PORTAL_SPAWN,
    /** Bukkit sound name */ BLOCK_FENCE_GATE_CLOSE,
    /** Bukkit sound name */ BLOCK_FENCE_GATE_OPEN,
    /** Bukkit sound name */ BLOCK_FIRE_AMBIENT("FIRE"),
    /** Bukkit sound name */ BLOCK_FIRE_EXTINGUISH("FIZZ"),
    /** Bukkit sound name */  BLOCK_FURNACE_FIRE_CRACKLE,
    /** Bukkit sound name */ BLOCK_GLASS_BREAK("GLASS"),
    /** Bukkit sound name */ BLOCK_GLASS_FALL,
    /** Bukkit sound name */ BLOCK_GLASS_HIT,
    /** Bukkit sound name */ BLOCK_GLASS_PLACE,
    /** Bukkit sound name */ BLOCK_GLASS_STEP,
    /** Bukkit sound name */ BLOCK_GRASS_BREAK("DIG_GRASS"),
    /** Bukkit sound name */ BLOCK_GRASS_FALL,
    /** Bukkit sound name */ BLOCK_GRASS_HIT,
    /** Bukkit sound name */ BLOCK_GRASS_PLACE,
    /** Bukkit sound name */ BLOCK_GRASS_STEP("STEP_GRASS"),
    /** Bukkit sound name */ BLOCK_GRAVEL_BREAK("DIG_GRAVEL"),
    /** Bukkit sound name */ BLOCK_GRAVEL_FALL,
    /** Bukkit sound name */ BLOCK_GRAVEL_HIT,
    /** Bukkit sound name */ BLOCK_GRAVEL_PLACE,
    /** Bukkit sound name */ BLOCK_GRAVEL_STEP("STEP_GRAVEL"),
    /** Bukkit sound name */ BLOCK_GRINDSTONE_USE,
    /** Bukkit sound name */ BLOCK_HONEY_BLOCK_BREAK,
    /** Bukkit sound name */ BLOCK_HONEY_BLOCK_FALL,
    /** Bukkit sound name */ BLOCK_HONEY_BLOCK_HIT,
    /** Bukkit sound name */ BLOCK_HONEY_BLOCK_PLACE,
    /** Bukkit sound name */ BLOCK_HONEY_BLOCK_SLIDE,
    /** Bukkit sound name */ BLOCK_HONEY_BLOCK_STEP,
    /** Bukkit sound name */ BLOCK_IRON_DOOR_CLOSE,
    /** Bukkit sound name */ BLOCK_IRON_DOOR_OPEN,
    /** Bukkit sound name */ BLOCK_IRON_TRAPDOOR_CLOSE,
    /** Bukkit sound name */ BLOCK_IRON_TRAPDOOR_OPEN,
    /** Bukkit sound name */ BLOCK_LADDER_BREAK,
    /** Bukkit sound name */ BLOCK_LADDER_FALL,
    /** Bukkit sound name */ BLOCK_LADDER_HIT,
    /** Bukkit sound name */ BLOCK_LADDER_PLACE,
    /** Bukkit sound name */ BLOCK_LADDER_STEP("STEP_LADDER"),
    /** Bukkit sound name */ BLOCK_LANTERN_BREAK,
    /** Bukkit sound name */ BLOCK_LANTERN_FALL,
    /** Bukkit sound name */ BLOCK_LANTERN_HIT,
    /** Bukkit sound name */ BLOCK_LANTERN_PLACE,
    /** Bukkit sound name */ BLOCK_LANTERN_STEP,
    /** Bukkit sound name */ BLOCK_LAVA_AMBIENT("LAVA"),
    /** Bukkit sound name */ BLOCK_LAVA_EXTINGUISH,
    /** Bukkit sound name */ BLOCK_LAVA_POP("LAVA_POP"),
    /** Bukkit sound name */ BLOCK_LEVER_CLICK,
    /** Bukkit sound name */ BLOCK_LILY_PAD_PLACE("BLOCK_WATERLILY_PLACE"),
    /** Bukkit sound name */ BLOCK_METAL_BREAK,
    /** Bukkit sound name */ BLOCK_METAL_FALL,
    /** Bukkit sound name */ BLOCK_METAL_HIT,
    /** Bukkit sound name */ BLOCK_METAL_PLACE,
    /** Bukkit sound name */ BLOCK_METAL_PRESSURE_PLATE_CLICK_OFF("BLOCK_METAL_PRESSUREPLATE_CLICK_OFF"),
    /** Bukkit sound name */ BLOCK_METAL_PRESSURE_PLATE_CLICK_ON("BLOCK_METAL_PRESSUREPLATE_CLICK_ON"),
    /** Bukkit sound name */ BLOCK_METAL_STEP,
    /** Bukkit sound name */ BLOCK_NETHER_WART_BREAK,
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_BANJO,
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_BASEDRUM("NOTE_BASS_DRUM", "BLOCK_NOTE_BASEDRUM"),
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_BASS("NOTE_BASS", "BLOCK_NOTE_BASS"),
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_BELL("BLOCK_NOTE_BELL"),
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_BIT,
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_CHIME("BLOCK_NOTE_CHIME"),
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_COW_BELL,
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_DIDGERIDOO,
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_FLUTE("BLOCK_NOTE_FLUTE"),
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_GUITAR("NOTE_BASS_GUITAR", "BLOCK_NOTE_GUITAR"),
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_HARP("NOTE_PIANO", "BLOCK_NOTE_HARP"),
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_HAT("NOTE_STICKS", "BLOCK_NOTE_HAT"),
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_IRON_XYLOPHONE,
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_PLING("NOTE_PLING", "BLOCK_NOTE_PLING"),
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_SNARE("NOTE_SNARE_DRUM", "BLOCK_NOTE_SNARE"),
    /** Bukkit sound name */ BLOCK_NOTE_BLOCK_XYLOPHONE("BLOCK_NOTE_XYLOPHONE"),
    /** Bukkit sound name */ BLOCK_PISTON_CONTRACT("PISTON_RETRACT"),
    /** Bukkit sound name */ BLOCK_PISTON_EXTEND("PISTON_EXTEND"),
    /** Bukkit sound name */ BLOCK_PORTAL_AMBIENT("PORTAL"),
    /** Bukkit sound name */ BLOCK_PORTAL_TRAVEL("PORTAL_TRAVEL"),
    /** Bukkit sound name */ BLOCK_PORTAL_TRIGGER("PORTAL_TRIGGER"),
    /** Bukkit sound name */ BLOCK_PUMPKIN_CARVE,
    /** Bukkit sound name */ BLOCK_REDSTONE_TORCH_BURNOUT,
    /** Bukkit sound name */ BLOCK_SAND_BREAK("DIG_SAND"),
    /** Bukkit sound name */ BLOCK_SAND_FALL,
    /** Bukkit sound name */ BLOCK_SAND_HIT,
    /** Bukkit sound name */ BLOCK_SAND_PLACE,
    /** Bukkit sound name */ BLOCK_SAND_STEP("STEP_SAND"),
    /** Bukkit sound name */ BLOCK_SCAFFOLDING_BREAK,
    /** Bukkit sound name */ BLOCK_SCAFFOLDING_FALL,
    /** Bukkit sound name */ BLOCK_SCAFFOLDING_HIT,
    /** Bukkit sound name */ BLOCK_SCAFFOLDING_PLACE,
    /** Bukkit sound name */ BLOCK_SCAFFOLDING_STEP,
    /** Bukkit sound name */ BLOCK_SHULKER_BOX_CLOSE,
    /** Bukkit sound name */ BLOCK_SHULKER_BOX_OPEN,
    /** Bukkit sound name */ BLOCK_SLIME_BLOCK_BREAK("BLOCK_SLIME_BREAK"),
    /** Bukkit sound name */ BLOCK_SLIME_BLOCK_FALL("BLOCK_SLIME_FALL"),
    /** Bukkit sound name */ BLOCK_SLIME_BLOCK_HIT("BLOCK_SLIME_HIT"),
    /** Bukkit sound name */ BLOCK_SLIME_BLOCK_PLACE("BLOCK_SLIME_PLACE"),
    /** Bukkit sound name */ BLOCK_SLIME_BLOCK_STEP("BLOCK_SLIME_STEP"),
    /** Bukkit sound name */ BLOCK_SMOKER_SMOKE,
    /** Bukkit sound name */ BLOCK_SNOW_BREAK("DIG_SNOW"),
    /** Bukkit sound name */ BLOCK_SNOW_FALL,
    /** Bukkit sound name */ BLOCK_SNOW_HIT,
    /** Bukkit sound name */ BLOCK_SNOW_PLACE,
    /** Bukkit sound name */ BLOCK_SNOW_STEP("STEP_SNOW"),
    /** Bukkit sound name */ BLOCK_STONE_BREAK("DIG_STONE"),
    /** Bukkit sound name */ BLOCK_STONE_BUTTON_CLICK_OFF,
    /** Bukkit sound name */ BLOCK_STONE_BUTTON_CLICK_ON,
    /** Bukkit sound name */ BLOCK_STONE_FALL,
    /** Bukkit sound name */ BLOCK_STONE_HIT,
    /** Bukkit sound name */ BLOCK_STONE_PLACE,
    /** Bukkit sound name */ BLOCK_STONE_PRESSURE_PLATE_CLICK_OFF("BLOCK_STONE_PRESSUREPLATE_CLICK_OFF"),
    /** Bukkit sound name */ BLOCK_STONE_PRESSURE_PLATE_CLICK_ON("BLOCK_STONE_PRESSUREPLATE_CLICK_ON"),
    /** Bukkit sound name */ BLOCK_STONE_STEP("STEP_STONE"),
    /** Bukkit sound name */ BLOCK_SWEET_BERRY_BUSH_BREAK,
    /** Bukkit sound name */ BLOCK_SWEET_BERRY_BUSH_PLACE,
    /** Bukkit sound name */ BLOCK_TRIPWIRE_ATTACH,
    /** Bukkit sound name */  BLOCK_TRIPWIRE_CLICK_OFF,
    /** Bukkit sound name */ BLOCK_TRIPWIRE_CLICK_ON,
    /** Bukkit sound name */ BLOCK_TRIPWIRE_DETACH,
    /** Bukkit sound name */ BLOCK_WATER_AMBIENT("WATER"),
    /** Bukkit sound name */ BLOCK_WET_GRASS_BREAK,
    /** Bukkit sound name */ BLOCK_WET_GRASS_FALL,
    /** Bukkit sound name */ BLOCK_WET_GRASS_HIT,
    /** Bukkit sound name */ BLOCK_WET_GRASS_PLACE("BLOCK_WET_GRASS_HIT"),
    /** Bukkit sound name */ BLOCK_WET_GRASS_STEP("BLOCK_WET_GRASS_HIT"),
    /** Bukkit sound name */ BLOCK_WOODEN_BUTTON_CLICK_OFF("WOOD_CLICK", "BLOCK_WOOD_BUTTON_CLICK_OFF"),
    /** Bukkit sound name */ BLOCK_WOODEN_BUTTON_CLICK_ON("WOOD_CLICK", "BLOCK_WOOD_BUTTON_CLICK_ON"),
    /** Bukkit sound name */ BLOCK_WOODEN_DOOR_CLOSE("DOOR_CLOSE"),
    /** Bukkit sound name */ BLOCK_WOODEN_DOOR_OPEN("DOOR_OPEN"),
    /** Bukkit sound name */ BLOCK_WOODEN_PRESSURE_PLATE_CLICK_OFF("BLOCK_WOOD_PRESSUREPLATE_CLICK_OFF"),
    /** Bukkit sound name */ BLOCK_WOODEN_PRESSURE_PLATE_CLICK_ON("BLOCK_WOOD_PRESSUREPLATE_CLICK_ON"),
    /** Bukkit sound name */ BLOCK_WOODEN_TRAPDOOR_CLOSE,
    /** Bukkit sound name */ BLOCK_WOODEN_TRAPDOOR_OPEN,
    /** Bukkit sound name */ BLOCK_WOOD_BREAK("DIG_WOOD"),
    /** Bukkit sound name */ BLOCK_WOOD_FALL,
    /** Bukkit sound name */ BLOCK_WOOD_HIT,
    /** Bukkit sound name */ BLOCK_WOOD_PLACE,
    /** Bukkit sound name */ BLOCK_WOOD_STEP("STEP_WOOD"),
    /** Bukkit sound name */ BLOCK_WOOL_BREAK("DIG_WOOL", "BLOCK_CLOTH_BREAK"),
    /** Bukkit sound name */ BLOCK_WOOL_FALL,
    /** Bukkit sound name */ BLOCK_WOOL_HIT("BLOCK_WOOL_FALL"),
    /** Bukkit sound name */ BLOCK_WOOL_PLACE("BLOCK_WOOL_FALL"),
    /** Bukkit sound name */ BLOCK_WOOL_STEP("STEP_WOOL", "BLOCK_CLOTH_STEP"),
    /** Bukkit sound name */ ENCHANT_THORNS_HIT,
    /** Bukkit sound name */ ENTITY_ARMOR_STAND_BREAK("ENTITY_ARMORSTAND_BREAK"),
    /** Bukkit sound name */ ENTITY_ARMOR_STAND_FALL("ENTITY_ARMORSTAND_FALL"),
    /** Bukkit sound name */ ENTITY_ARMOR_STAND_HIT("ENTITY_ARMORSTAND_HIT"),
    /** Bukkit sound name */ ENTITY_ARMOR_STAND_PLACE("ENTITY_ARMORSTAND_PLACE"),
    /** Bukkit sound name */ ENTITY_ARROW_HIT("ARROW_HIT"),
    /** Bukkit sound name */ ENTITY_ARROW_HIT_PLAYER,
    /** Bukkit sound name */ ENTITY_ARROW_SHOOT("SHOOT_ARROW"),
    /** Bukkit sound name */ ENTITY_BAT_AMBIENT("BAT_IDLE"),
    /** Bukkit sound name */ ENTITY_BAT_DEATH("BAT_DEATH"),
    /** Bukkit sound name */ ENTITY_BAT_HURT("BAT_HURT"),
    /** Bukkit sound name */ ENTITY_BAT_LOOP("BAT_LOOP"),
    /** Bukkit sound name */ ENTITY_BAT_TAKEOFF("BAT_TAKEOFF"),
    /** Bukkit sound name */ ENTITY_BEE_DEATH,
    /** Bukkit sound name */ ENTITY_BEE_HURT,
    /** Bukkit sound name */ ENTITY_BEE_LOOP,
    /** Bukkit sound name */ ENTITY_BEE_LOOP_AGGRESSIVE,
    /** Bukkit sound name */ ENTITY_BEE_POLLINATE,
    /** Bukkit sound name */ ENTITY_BEE_STING,
    /** Bukkit sound name */ ENTITY_BLAZE_AMBIENT("BLAZE_BREATH"),
    /** Bukkit sound name */ ENTITY_BLAZE_BURN,
    /** Bukkit sound name */ ENTITY_BLAZE_DEATH("BLAZE_DEATH"),
    /** Bukkit sound name */ ENTITY_BLAZE_HURT("BLAZE_HIT"),
    /** Bukkit sound name */ ENTITY_BLAZE_SHOOT,
    /** Bukkit sound name */ ENTITY_BOAT_PADDLE_LAND,
    /** Bukkit sound name */ ENTITY_BOAT_PADDLE_WATER,
    /** Bukkit sound name */ ENTITY_CAT_AMBIENT("CAT_MEOW"),
    /** Bukkit sound name */ ENTITY_CAT_BEG_FOR_FOOD,
    /** Bukkit sound name */ ENTITY_CAT_DEATH,
    /** Bukkit sound name */ ENTITY_CAT_EAT,
    /** Bukkit sound name */ ENTITY_CAT_HISS("CAT_HISS"),
    /** Bukkit sound name */ ENTITY_CAT_HURT("CAT_HIT"),
    /** Bukkit sound name */ ENTITY_CAT_PURR("CAT_PURR"),
    /** Bukkit sound name */ ENTITY_CAT_PURREOW("CAT_PURREOW"),
    /** Bukkit sound name */ ENTITY_CAT_STRAY_AMBIENT,
    /** Bukkit sound name */ ENTITY_CHICKEN_AMBIENT("CHICKEN_IDLE"),
    /** Bukkit sound name */ ENTITY_CHICKEN_DEATH,
    /** Bukkit sound name */ ENTITY_CHICKEN_EGG("CHICKEN_EGG_POP"),
    /** Bukkit sound name */ ENTITY_CHICKEN_HURT("CHICKEN_HURT"),
    /** Bukkit sound name */ ENTITY_CHICKEN_STEP("CHICKEN_WALK"),
    /** Bukkit sound name */ ENTITY_COD_AMBIENT,
    /** Bukkit sound name */ ENTITY_COD_DEATH,
    /** Bukkit sound name */ ENTITY_COD_FLOP,
    /** Bukkit sound name */ ENTITY_COD_HURT,
    /** Bukkit sound name */ ENTITY_COW_AMBIENT("COW_IDLE"),
    /** Bukkit sound name */ ENTITY_COW_DEATH,
    /** Bukkit sound name */ ENTITY_COW_HURT("COW_HURT"),
    /** Bukkit sound name */ ENTITY_COW_MILK,
    /** Bukkit sound name */ ENTITY_COW_STEP("COW_WALK"),
    /** Bukkit sound name */ ENTITY_CREEPER_DEATH("CREEPER_DEATH"),
    /** Bukkit sound name */ ENTITY_CREEPER_HURT,
    /** Bukkit sound name */ ENTITY_CREEPER_PRIMED("CREEPER_HISS"),
    /** Bukkit sound name */ ENTITY_DOLPHIN_AMBIENT,
    /** Bukkit sound name */ ENTITY_DOLPHIN_AMBIENT_WATER,
    /** Bukkit sound name */ ENTITY_DOLPHIN_ATTACK,
    /** Bukkit sound name */ ENTITY_DOLPHIN_DEATH,
    /** Bukkit sound name */ ENTITY_DOLPHIN_EAT,
    /** Bukkit sound name */ ENTITY_DOLPHIN_HURT,
    /** Bukkit sound name */ ENTITY_DOLPHIN_JUMP,
    /** Bukkit sound name */ ENTITY_DOLPHIN_PLAY,
    /** Bukkit sound name */ ENTITY_DOLPHIN_SPLASH,
    /** Bukkit sound name */ ENTITY_DOLPHIN_SWIM,
    /** Bukkit sound name */ ENTITY_DONKEY_AMBIENT("DONKEY_IDLE"),
    /** Bukkit sound name */ ENTITY_DONKEY_ANGRY("DONKEY_ANGRY"),
    /** Bukkit sound name */ ENTITY_DONKEY_CHEST,
    /** Bukkit sound name */ ENTITY_DONKEY_DEATH("DONKEY_DEATH"),
    /** Bukkit sound name */ ENTITY_DONKEY_HURT("DONKEY_HIT"),
    /** Bukkit sound name */ ENTITY_DRAGON_FIREBALL_EXPLODE("ENTITY_ENDERDRAGON_FIREBALL_EXPLODE"),
    /** Bukkit sound name */ ENTITY_DROWNED_AMBIENT,
    /** Bukkit sound name */ ENTITY_DROWNED_AMBIENT_WATER,
    /** Bukkit sound name */ ENTITY_DROWNED_DEATH,
    /** Bukkit sound name */ ENTITY_DROWNED_DEATH_WATER,
    /** Bukkit sound name */ ENTITY_DROWNED_HURT,
    /** Bukkit sound name */ ENTITY_DROWNED_HURT_WATER,
    /** Bukkit sound name */ ENTITY_DROWNED_SHOOT,
    /** Bukkit sound name */ ENTITY_DROWNED_STEP,
    /** Bukkit sound name */ ENTITY_DROWNED_SWIM,
    /** Bukkit sound name */ ENTITY_EGG_THROW,
    /** Bukkit sound name */ ENTITY_ELDER_GUARDIAN_AMBIENT,
    /** Bukkit sound name */ ENTITY_ELDER_GUARDIAN_AMBIENT_LAND,
    /** Bukkit sound name */ ENTITY_ELDER_GUARDIAN_CURSE,
    /** Bukkit sound name */ ENTITY_ELDER_GUARDIAN_DEATH,
    /** Bukkit sound name */ ENTITY_ELDER_GUARDIAN_DEATH_LAND,
    /** Bukkit sound name */ ENTITY_ELDER_GUARDIAN_FLOP,
    /** Bukkit sound name */ ENTITY_ELDER_GUARDIAN_HURT,
    /** Bukkit sound name */ ENTITY_ELDER_GUARDIAN_HURT_LAND,
    /** Bukkit sound name */ ENTITY_ENDERMAN_AMBIENT("ENDERMAN_IDLE", "ENTITY_ENDERMEN_AMBIENT"),
    /** Bukkit sound name */ ENTITY_ENDERMAN_DEATH("ENDERMAN_DEATH", "ENTITY_ENDERMEN_DEATH"),
    /** Bukkit sound name */ ENTITY_ENDERMAN_HURT("ENDERMAN_HIT", "ENTITY_ENDERMEN_HURT"),
    /** Bukkit sound name */ ENTITY_ENDERMAN_SCREAM("ENDERMAN_SCREAM", "ENTITY_ENDERMEN_SCREAM"),
    /** Bukkit sound name */ ENTITY_ENDERMAN_STARE("ENDERMAN_STARE", "ENTITY_ENDERMEN_STARE"),
    /** Bukkit sound name */ ENTITY_ENDERMAN_TELEPORT("ENDERMAN_TELEPORT", "ENTITY_ENDERMEN_TELEPORT"),
    /** Bukkit sound name */ ENTITY_ENDERMITE_AMBIENT,
    /** Bukkit sound name */ ENTITY_ENDERMITE_DEATH,
    /** Bukkit sound name */ ENTITY_ENDERMITE_HURT,
    /** Bukkit sound name */ ENTITY_ENDERMITE_STEP,
    /** Bukkit sound name */ ENTITY_ENDER_DRAGON_AMBIENT("ENDERDRAGON_WINGS", "ENTITY_ENDERDRAGON_AMBIENT"),
    /** Bukkit sound name */ ENTITY_ENDER_DRAGON_DEATH("ENDERDRAGON_DEATH", "ENTITY_ENDERDRAGON_DEATH"),
    /** Bukkit sound name */ ENTITY_ENDER_DRAGON_FLAP("ENDERDRAGON_WINGS", "ENTITY_ENDERDRAGON_FLAP"),
    /** Bukkit sound name */ ENTITY_ENDER_DRAGON_GROWL("ENDERDRAGON_GROWL", "ENTITY_ENDERDRAGON_GROWL"),
    /** Bukkit sound name */ ENTITY_ENDER_DRAGON_HURT("ENDERDRAGON_HIT", "ENTITY_ENDERDRAGON_HURT"),
    /** Bukkit sound name */ ENTITY_ENDER_DRAGON_SHOOT("ENTITY_ENDERDRAGON_SHOOT"),
    /** Bukkit sound name */ ENTITY_ENDER_EYE_DEATH,
    /** Bukkit sound name */ ENTITY_ENDER_EYE_LAUNCH("ENTITY_ENDER_EYE_DEATH", "ENTITY_ENDEREYE_DEATH"),
    /** Bukkit sound name */ ENTITY_ENDER_PEARL_THROW("ENTITY_ENDERPEARL_THROW"),
    /** Bukkit sound name */ ENTITY_EVOKER_AMBIENT("ENTITY_EVOCATION_ILLAGER_AMBIENT"),
    /** Bukkit sound name */ ENTITY_EVOKER_CAST_SPELL("ENTITY_EVOCATION_ILLAGER_CAST_SPELL"),
    /** Bukkit sound name */ ENTITY_EVOKER_CELEBRATE,
    /** Bukkit sound name */ ENTITY_EVOKER_DEATH("ENTITY_EVOCATION_ILLAGER_DEATH"),
    /** Bukkit sound name */ ENTITY_EVOKER_FANGS_ATTACK("ENTITY_EVOCATION_FANGS_ATTACK"),
    /** Bukkit sound name */ ENTITY_EVOKER_HURT("ENTITY_EVOCATION_ILLAGER_HURT"),
    /** Bukkit sound name */ ENTITY_EVOKER_PREPARE_ATTACK("ENTITY_EVOCATION_ILLAGER_PREPARE_ATTACK"),
    /** Bukkit sound name */ ENTITY_EVOKER_PREPARE_SUMMON("ENTITY_EVOCATION_ILLAGER_PREPARE_SUMMON"),
    /** Bukkit sound name */ ENTITY_EVOKER_PREPARE_WOLOLO("ENTITY_EVOCATION_ILLAGER_PREPARE_WOLOLO"),
    /** Bukkit sound name */ ENTITY_EXPERIENCE_BOTTLE_THROW,
    /** Bukkit sound name */ ENTITY_EXPERIENCE_ORB_PICKUP("ORB_PICKUP"),
    /** Bukkit sound name */ ENTITY_FIREWORK_ROCKET_BLAST("FIREWORK_BLAST", "ENTITY_FIREWORK_BLAST"),
    /** Bukkit sound name */ ENTITY_FIREWORK_ROCKET_BLAST_FAR("FIREWORK_BLAST2", "ENTITY_FIREWORK_BLAST_FAR"),
    /** Bukkit sound name */ ENTITY_FIREWORK_ROCKET_LARGE_BLAST("FIREWORK_LARGE_BLAST", "ENTITY_FIREWORK_LARGE_BLAST"),
    /** Bukkit sound name */ ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR("FIREWORK_LARGE_BLAST2", "ENTITY_FIREWORK_LARGE_BLAST_FAR"),
    /** Bukkit sound name */ ENTITY_FIREWORK_ROCKET_LAUNCH("FIREWORK_LAUNCH", "ENTITY_FIREWORK_LAUNCH"),
    /** Bukkit sound name */ ENTITY_FIREWORK_ROCKET_SHOOT,
    /** Bukkit sound name */ ENTITY_FIREWORK_ROCKET_TWINKLE("FIREWORK_TWINKLE", "ENTITY_FIREWORK_TWINKLE"),
    /** Bukkit sound name */ ENTITY_FIREWORK_ROCKET_TWINKLE_FAR("FIREWORK_TWINKLE2", "ENTITY_FIREWORK_TWINKLE_FAR"),
    /** Bukkit sound name */ ENTITY_FISHING_BOBBER_RETRIEVE,
    /** Bukkit sound name */ ENTITY_FISHING_BOBBER_SPLASH("SPLASH2", "ENTITY_BOBBER_SPLASH"),
    /** Bukkit sound name */ ENTITY_FISHING_BOBBER_THROW("ENTITY_BOBBER_THROW"),
    /** Bukkit sound name */ ENTITY_FISH_SWIM,
    /** Bukkit sound name */ ENTITY_FOX_AGGRO,
    /** Bukkit sound name */ ENTITY_FOX_AMBIENT,
    /** Bukkit sound name */ ENTITY_FOX_BITE,
    /** Bukkit sound name */ ENTITY_FOX_DEATH,
    /** Bukkit sound name */ ENTITY_FOX_EAT,
    /** Bukkit sound name */ ENTITY_FOX_HURT,
    /** Bukkit sound name */ ENTITY_FOX_SCREECH,
    /** Bukkit sound name */ ENTITY_FOX_SLEEP,
    /** Bukkit sound name */ ENTITY_FOX_SNIFF,
    /** Bukkit sound name */ ENTITY_FOX_SPIT,
    /** Bukkit sound name */ ENTITY_GENERIC_BIG_FALL("FALL_BIG"),
    /** Bukkit sound name */ ENTITY_GENERIC_BURN,
    /** Bukkit sound name */ ENTITY_GENERIC_DEATH,
    /** Bukkit sound name */ ENTITY_GENERIC_DRINK("DRINK"),
    /** Bukkit sound name */ ENTITY_GENERIC_EAT("EAT"),
    /** Bukkit sound name */ ENTITY_GENERIC_EXPLODE("EXPLODE"),
    /** Bukkit sound name */ ENTITY_GENERIC_EXTINGUISH_FIRE,
    /** Bukkit sound name */ ENTITY_GENERIC_HURT,
    /** Bukkit sound name */ ENTITY_GENERIC_SMALL_FALL("FALL_SMALL"),
    /** Bukkit sound name */ ENTITY_GENERIC_SPLASH("SPLASH"),
    /** Bukkit sound name */ ENTITY_GENERIC_SWIM("SWIM"),
    /** Bukkit sound name */ ENTITY_GHAST_AMBIENT("GHAST_MOAN"),
    /** Bukkit sound name */ ENTITY_GHAST_DEATH("GHAST_DEATH"),
    /** Bukkit sound name */ ENTITY_GHAST_HURT("GHAST_SCREAM2"),
    /** Bukkit sound name */ ENTITY_GHAST_SCREAM("GHAST_SCREAM"),
    /** Bukkit sound name */ ENTITY_GHAST_SHOOT("GHAST_FIREBALL"),
    /** Bukkit sound name */ ENTITY_GHAST_WARN("GHAST_CHARGE"),
    /** Bukkit sound name */ ENTITY_GUARDIAN_AMBIENT,
    /** Bukkit sound name */ ENTITY_GUARDIAN_AMBIENT_LAND,
    /** Bukkit sound name */ ENTITY_GUARDIAN_ATTACK,
    /** Bukkit sound name */ ENTITY_GUARDIAN_DEATH,
    /** Bukkit sound name */ ENTITY_GUARDIAN_DEATH_LAND,
    /** Bukkit sound name */ ENTITY_GUARDIAN_FLOP,
    /** Bukkit sound name */ ENTITY_GUARDIAN_HURT,
    /** Bukkit sound name */ ENTITY_GUARDIAN_HURT_LAND,
    /** Bukkit sound name */ ENTITY_HORSE_AMBIENT("HORSE_IDLE"),
    /** Bukkit sound name */ ENTITY_HORSE_ANGRY("HORSE_ANGRY"),
    /** Bukkit sound name */ ENTITY_HORSE_ARMOR("HORSE_ARMOR"),
    /** Bukkit sound name */ ENTITY_HORSE_BREATHE("HORSE_BREATHE"),
    /** Bukkit sound name */ ENTITY_HORSE_DEATH("HORSE_DEATH"),
    /** Bukkit sound name */ ENTITY_HORSE_EAT,
    /** Bukkit sound name */ ENTITY_HORSE_GALLOP("HORSE_GALLOP"),
    /** Bukkit sound name */ ENTITY_HORSE_HURT("HORSE_HIT"),
    /** Bukkit sound name */ ENTITY_HORSE_JUMP("HORSE_JUMP"),
    /** Bukkit sound name */ ENTITY_HORSE_LAND("HORSE_LAND"),
    /** Bukkit sound name */ ENTITY_HORSE_SADDLE("HORSE_SADDLE"),
    /** Bukkit sound name */ ENTITY_HORSE_STEP("HORSE_SOFT"),
    /** Bukkit sound name */ ENTITY_HORSE_STEP_WOOD("HORSE_WOOD"),
    /** Bukkit sound name */ ENTITY_HOSTILE_BIG_FALL("FALL_BIG"),
    /** Bukkit sound name */ ENTITY_HOSTILE_DEATH,
    /** Bukkit sound name */ ENTITY_HOSTILE_HURT,
    /** Bukkit sound name */ ENTITY_HOSTILE_SMALL_FALL("FALL_SMALL"),
    /** Bukkit sound name */ ENTITY_HOSTILE_SPLASH("SPLASH"),
    /** Bukkit sound name */ ENTITY_HOSTILE_SWIM("SWIM"),
    /** Bukkit sound name */ ENTITY_HUSK_AMBIENT,
    /** Bukkit sound name */ ENTITY_HUSK_CONVERTED_TO_ZOMBIE,
    /** Bukkit sound name */ ENTITY_HUSK_DEATH,
    /** Bukkit sound name */ ENTITY_HUSK_HURT,
    /** Bukkit sound name */ ENTITY_HUSK_STEP,
    /** Bukkit sound name */ ENTITY_ILLUSIONER_AMBIENT("ENTITY_ILLUSION_ILLAGER_AMBIENT"),
    /** Bukkit sound name */ ENTITY_ILLUSIONER_CAST_SPELL("ENTITY_ILLUSION_ILLAGER_CAST_SPELL"),
    /** Bukkit sound name */ ENTITY_ILLUSIONER_DEATH("ENTITY_ILLUSIONER_CAST_DEATH", "ENTITY_ILLUSION_ILLAGER_DEATH"),
    /** Bukkit sound name */ ENTITY_ILLUSIONER_HURT("ENTITY_ILLUSION_ILLAGER_HURT"),
    /** Bukkit sound name */ ENTITY_ILLUSIONER_MIRROR_MOVE("ENTITY_ILLUSION_ILLAGER_MIRROR_MOVE"),
    /** Bukkit sound name */  ENTITY_ILLUSIONER_PREPARE_BLINDNESS("ENTITY_ILLUSION_ILLAGER_PREPARE_BLINDNESS"),
    /** Bukkit sound name */ ENTITY_ILLUSIONER_PREPARE_MIRROR("ENTITY_ILLUSION_ILLAGER_PREPARE_MIRROR"),
    /** Bukkit sound name */ ENTITY_IRON_GOLEM_ATTACK("IRONGOLEM_THROW", "ENTITY_IRONGOLEM_ATTACK"),
    /** Bukkit sound name */ ENTITY_IRON_GOLEM_DAMAGE,
    /** Bukkit sound name */ ENTITY_IRON_GOLEM_DEATH("IRONGOLEM_DEATH", "ENTITY_IRONGOLEM_DEATH"),
    /** Bukkit sound name */ ENTITY_IRON_GOLEM_HURT("IRONGOLEM_HIT", "ENTITY_IRONGOLEM_HURT"),
    /** Bukkit sound name */ ENTITY_IRON_GOLEM_REPAIR,
    /** Bukkit sound name */ ENTITY_IRON_GOLEM_STEP("IRONGOLEM_WALK", "ENTITY_IRONGOLEM_STEP"),
    /** Bukkit sound name */ ENTITY_ITEM_BREAK("ITEM_BREAK"),
    /** Bukkit sound name */ ENTITY_ITEM_FRAME_ADD_ITEM("ENTITY_ITEMFRAME_ADD_ITEM"),
    /** Bukkit sound name */ ENTITY_ITEM_FRAME_BREAK("ENTITY_ITEMFRAME_BREAK"),
    /** Bukkit sound name */ ENTITY_ITEM_FRAME_PLACE("ENTITY_ITEMFRAME_PLACE"),
    /** Bukkit sound name */ ENTITY_ITEM_FRAME_REMOVE_ITEM("ENTITY_ITEMFRAME_REMOVE_ITEM"),
    /** Bukkit sound name */ ENTITY_ITEM_FRAME_ROTATE_ITEM("ENTITY_ITEMFRAME_ROTATE_ITEM"),
    /** Bukkit sound name */ ENTITY_ITEM_PICKUP("ITEM_PICKUP"),
    /** Bukkit sound name */ ENTITY_LEASH_KNOT_BREAK("ENTITY_LEASHKNOT_BREAK"),
    /** Bukkit sound name */ ENTITY_LEASH_KNOT_PLACE("ENTITY_LEASHKNOT_PLACE"),
    /** Bukkit sound name */ ENTITY_LIGHTNING_BOLT_IMPACT("AMBIENCE_THUNDER", "ENTITY_LIGHTNING_IMPACT"),
    /** Bukkit sound name */ ENTITY_LIGHTNING_BOLT_THUNDER("AMBIENCE_THUNDER", "ENTITY_LIGHTNING_THUNDER"),
    /** Bukkit sound name */ ENTITY_LINGERING_POTION_THROW,
    /** Bukkit sound name */ ENTITY_LLAMA_AMBIENT,
    /** Bukkit sound name */ ENTITY_LLAMA_ANGRY,
    /** Bukkit sound name */ ENTITY_LLAMA_CHEST,
    /** Bukkit sound name */ ENTITY_LLAMA_DEATH,
    /** Bukkit sound name */ ENTITY_LLAMA_EAT,
    /** Bukkit sound name */ ENTITY_LLAMA_HURT,
    /** Bukkit sound name */ ENTITY_LLAMA_SPIT,
    /** Bukkit sound name */ ENTITY_LLAMA_STEP,
    /** Bukkit sound name */ ENTITY_LLAMA_SWAG,
    /** Bukkit sound name */ ENTITY_MAGMA_CUBE_DEATH("ENTITY_MAGMACUBE_DEATH"),
    /** Bukkit sound name */ ENTITY_MAGMA_CUBE_DEATH_SMALL("ENTITY_SMALL_MAGMACUBE_DEATH"),
    /** Bukkit sound name */ ENTITY_MAGMA_CUBE_HURT("ENTITY_MAGMACUBE_HURT"),
    /** Bukkit sound name */ ENTITY_MAGMA_CUBE_HURT_SMALL("ENTITY_SMALL_MAGMACUBE_HURT"),
    /** Bukkit sound name */ ENTITY_MAGMA_CUBE_JUMP("MAGMACUBE_JUMP", "ENTITY_MAGMACUBE_JUMP"),
    /** Bukkit sound name */ ENTITY_MAGMA_CUBE_SQUISH("MAGMACUBE_WALK", "ENTITY_MAGMACUBE_SQUISH"),
    /** Bukkit sound name */ ENTITY_MAGMA_CUBE_SQUISH_SMALL("MAGMACUBE_WALK2", "ENTITY_SMALL_MAGMACUBE_SQUISH"),
    /** Bukkit sound name */ ENTITY_MINECART_INSIDE("MINECART_INSIDE"),
    /** Bukkit sound name */ ENTITY_MINECART_RIDING("MINECART_BASE"),
    /** Bukkit sound name */ ENTITY_MOOSHROOM_CONVERT,
    /** Bukkit sound name */ ENTITY_MOOSHROOM_EAT,
    /** Bukkit sound name */ ENTITY_MOOSHROOM_MILK,
    /** Bukkit sound name */ ENTITY_MOOSHROOM_SHEAR,
    /** Bukkit sound name */ ENTITY_MOOSHROOM_SUSPICIOUS_MILK,
    /** Bukkit sound name */ ENTITY_MULE_AMBIENT,
    /** Bukkit sound name */ ENTITY_MULE_CHEST("ENTITY_MULE_AMBIENT"),
    /** Bukkit sound name */ ENTITY_MULE_DEATH("ENTITY_MULE_AMBIENT"),
    /** Bukkit sound name */ ENTITY_MULE_HURT("ENTITY_MULE_AMBIENT"),
    /** Bukkit sound name */ ENTITY_OCELOT_AMBIENT,
    /** Bukkit sound name */ ENTITY_OCELOT_DEATH,
    /** Bukkit sound name */ ENTITY_OCELOT_HURT,
    /** Bukkit sound name */ ENTITY_PAINTING_BREAK,
    /** Bukkit sound name */ ENTITY_PAINTING_PLACE,
    /** Bukkit sound name */ ENTITY_PANDA_AGGRESSIVE_AMBIENT,
    /** Bukkit sound name */ ENTITY_PANDA_AMBIENT,
    /** Bukkit sound name */ ENTITY_PANDA_BITE,
    /** Bukkit sound name */ ENTITY_PANDA_CANT_BREED,
    /** Bukkit sound name */ ENTITY_PANDA_DEATH,
    /** Bukkit sound name */ ENTITY_PANDA_EAT,
    /** Bukkit sound name */ ENTITY_PANDA_HURT,
    /** Bukkit sound name */ ENTITY_PANDA_PRE_SNEEZE,
    /** Bukkit sound name */ ENTITY_PANDA_SNEEZE,
    /** Bukkit sound name */ ENTITY_PANDA_STEP,
    /** Bukkit sound name */ ENTITY_PANDA_WORRIED_AMBIENT,
    /** Bukkit sound name */ ENTITY_PARROT_AMBIENT,
    /** Bukkit sound name */ ENTITY_PARROT_DEATH,
    /** Bukkit sound name */ ENTITY_PARROT_EAT,
    /** Bukkit sound name */ ENTITY_PARROT_FLY,
    /** Bukkit sound name */ ENTITY_PARROT_HURT,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_BLAZE,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_CREEPER,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_DROWNED,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_ELDER_GUARDIAN,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_ENDERMAN,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_ENDERMITE,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_ENDER_DRAGON,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_EVOKER,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_GHAST,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_GUARDIAN,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_HUSK,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_ILLUSIONER,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_MAGMA_CUBE,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_PHANTOM,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_PILLAGER,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_POLAR_BEAR,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_RAVAGER,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_SHULKER,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_SILVERFISH,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_SKELETON,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_SLIME,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_SPIDER,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_STRAY,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_VEX,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_VINDICATOR,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_WITCH,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_WITHER,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_WITHER_SKELETON,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_WOLF,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_ZOMBIE,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_ZOMBIE_PIGMAN,
    /** Bukkit sound name */ ENTITY_PARROT_IMITATE_ZOMBIE_VILLAGER,
    /** Bukkit sound name */ ENTITY_PARROT_STEP,
    /** Bukkit sound name */ ENTITY_PHANTOM_AMBIENT,
    /** Bukkit sound name */ ENTITY_PHANTOM_BITE,
    /** Bukkit sound name */ ENTITY_PHANTOM_DEATH,
    /** Bukkit sound name */ ENTITY_PHANTOM_FLAP,
    /** Bukkit sound name */ ENTITY_PHANTOM_HURT,
    /** Bukkit sound name */ ENTITY_PHANTOM_SWOOP,
    /** Bukkit sound name */ ENTITY_PIG_AMBIENT("PIG_IDLE"),
    /** Bukkit sound name */ ENTITY_PIG_DEATH("PIG_DEATH"),
    /** Bukkit sound name */ ENTITY_PIG_HURT,
    /** Bukkit sound name */ ENTITY_PIG_SADDLE("ENTITY_PIG_HURT"),
    /** Bukkit sound name */ ENTITY_PIG_STEP("PIG_WALK"),
    /** Bukkit sound name */ ENTITY_PILLAGER_AMBIENT,
    /** Bukkit sound name */ ENTITY_PILLAGER_CELEBRATE,
    /** Bukkit sound name */ ENTITY_PILLAGER_DEATH,
    /** Bukkit sound name */ ENTITY_PILLAGER_HURT,
    /** Bukkit sound name */ ENTITY_PLAYER_ATTACK_CRIT,
    /** Bukkit sound name */ ENTITY_PLAYER_ATTACK_KNOCKBACK,
    /** Bukkit sound name */ ENTITY_PLAYER_ATTACK_NODAMAGE,
    /** Bukkit sound name */ ENTITY_PLAYER_ATTACK_STRONG("SUCCESSFUL_HIT"),
    /** Bukkit sound name */ ENTITY_PLAYER_ATTACK_SWEEP,
    /** Bukkit sound name */ ENTITY_PLAYER_ATTACK_WEAK,
    /** Bukkit sound name */ ENTITY_PLAYER_BIG_FALL("FALL_BIG"),
    /** Bukkit sound name */ ENTITY_PLAYER_BREATH,
    /** Bukkit sound name */ ENTITY_PLAYER_BURP("BURP"),
    /** Bukkit sound name */ ENTITY_PLAYER_DEATH,
    /** Bukkit sound name */ ENTITY_PLAYER_HURT("HURT_FLESH"),
    /** Bukkit sound name */ ENTITY_PLAYER_HURT_DROWN,
    /** Bukkit sound name */ ENTITY_PLAYER_HURT_ON_FIRE,
    /** Bukkit sound name */ ENTITY_PLAYER_HURT_SWEET_BERRY_BUSH,
    /** Bukkit sound name */ ENTITY_PLAYER_LEVELUP("LEVEL_UP"),
    /** Bukkit sound name */ ENTITY_PLAYER_SMALL_FALL("FALL_SMALL"),
    /** Bukkit sound name */ ENTITY_PLAYER_SPLASH("SLASH"),
    /** Bukkit sound name */ ENTITY_PLAYER_SPLASH_HIGH_SPEED("SPLASH"),
    /** Bukkit sound name */ ENTITY_PLAYER_SWIM("SWIM"),
    /** Bukkit sound name */ ENTITY_POLAR_BEAR_AMBIENT,
    /** Bukkit sound name */ ENTITY_POLAR_BEAR_AMBIENT_BABY("ENTITY_POLAR_BEAR_BABY_AMBIENT"),
    /** Bukkit sound name */ ENTITY_POLAR_BEAR_DEATH,
    /** Bukkit sound name */ ENTITY_POLAR_BEAR_HURT,
    /** Bukkit sound name */ ENTITY_POLAR_BEAR_STEP,
    /** Bukkit sound name */ ENTITY_POLAR_BEAR_WARNING,
    /** Bukkit sound name */ ENTITY_PUFFER_FISH_AMBIENT,
    /** Bukkit sound name */ ENTITY_PUFFER_FISH_BLOW_OUT,
    /** Bukkit sound name */ ENTITY_PUFFER_FISH_BLOW_UP,
    /** Bukkit sound name */ ENTITY_PUFFER_FISH_DEATH,
    /** Bukkit sound name */ ENTITY_PUFFER_FISH_FLOP,
    /** Bukkit sound name */ ENTITY_PUFFER_FISH_HURT,
    /** Bukkit sound name */ ENTITY_PUFFER_FISH_STING,
    /** Bukkit sound name */ ENTITY_RABBIT_AMBIENT,
    /** Bukkit sound name */ ENTITY_RABBIT_ATTACK,
    /** Bukkit sound name */ ENTITY_RABBIT_DEATH,
    /** Bukkit sound name */ ENTITY_RABBIT_HURT,
    /** Bukkit sound name */ ENTITY_RABBIT_JUMP,
    /** Bukkit sound name */ ENTITY_RAVAGER_AMBIENT,
    /** Bukkit sound name */ ENTITY_RAVAGER_ATTACK,
    /** Bukkit sound name */ ENTITY_RAVAGER_CELEBRATE,
    /** Bukkit sound name */ ENTITY_RAVAGER_DEATH,
    /** Bukkit sound name */ ENTITY_RAVAGER_HURT,
    /** Bukkit sound name */ ENTITY_RAVAGER_ROAR,
    /** Bukkit sound name */ ENTITY_RAVAGER_STEP,
    /** Bukkit sound name */ ENTITY_RAVAGER_STUNNED,
    /** Bukkit sound name */ ENTITY_SALMON_AMBIENT,
    /** Bukkit sound name */ ENTITY_SALMON_DEATH,
    /** Bukkit sound name */ ENTITY_SALMON_FLOP,
    /** Bukkit sound name */ ENTITY_SALMON_HURT("ENTITY_SALMON_FLOP"),
    /** Bukkit sound name */ ENTITY_SHEEP_AMBIENT("SHEEP_IDLE"),
    /** Bukkit sound name */ ENTITY_SHEEP_DEATH,
    /** Bukkit sound name */ ENTITY_SHEEP_HURT,
    /** Bukkit sound name */ ENTITY_SHEEP_SHEAR("SHEEP_SHEAR"),
    /** Bukkit sound name */ ENTITY_SHEEP_STEP("SHEEP_WALK"),
    /** Bukkit sound name */ ENTITY_SHULKER_AMBIENT,
    /** Bukkit sound name */ ENTITY_SHULKER_BULLET_HIT,
    /** Bukkit sound name */ ENTITY_SHULKER_BULLET_HURT,
    /** Bukkit sound name */ ENTITY_SHULKER_CLOSE,
    /** Bukkit sound name */ ENTITY_SHULKER_DEATH,
    /** Bukkit sound name */ ENTITY_SHULKER_HURT,
    /** Bukkit sound name */ ENTITY_SHULKER_HURT_CLOSED,
    /** Bukkit sound name */ ENTITY_SHULKER_OPEN,
    /** Bukkit sound name */ ENTITY_SHULKER_SHOOT,
    /** Bukkit sound name */ ENTITY_SHULKER_TELEPORT,
    /** Bukkit sound name */ ENTITY_SILVERFISH_AMBIENT("SILVERFISH_IDLE"),
    /** Bukkit sound name */ ENTITY_SILVERFISH_DEATH("SILVERFISH_KILL"),
    /** Bukkit sound name */ ENTITY_SILVERFISH_HURT("SILVERFISH_HIT"),
    /** Bukkit sound name */ ENTITY_SILVERFISH_STEP("SILVERFISH_WALK"),
    /** Bukkit sound name */ ENTITY_SKELETON_AMBIENT("SKELETON_IDLE"),
    /** Bukkit sound name */ ENTITY_SKELETON_DEATH("SKELETON_DEATH"),
    /** Bukkit sound name */ ENTITY_SKELETON_HORSE_AMBIENT("HORSE_SKELETON_IDLE"),
    /** Bukkit sound name */ ENTITY_SKELETON_HORSE_AMBIENT_WATER,
    /** Bukkit sound name */ ENTITY_SKELETON_HORSE_DEATH("HORSE_SKELETON_DEATH"),
    /** Bukkit sound name */ ENTITY_SKELETON_HORSE_GALLOP_WATER,
    /** Bukkit sound name */ ENTITY_SKELETON_HORSE_HURT("HORSE_SKELETON_HIT"),
    /** Bukkit sound name */ ENTITY_SKELETON_HORSE_JUMP_WATER,
    /** Bukkit sound name */ ENTITY_SKELETON_HORSE_STEP_WATER,
    /** Bukkit sound name */ ENTITY_SKELETON_HORSE_SWIM,
    /** Bukkit sound name */ ENTITY_SKELETON_HURT("SKELETON_HURT"),
    /** Bukkit sound name */ ENTITY_SKELETON_SHOOT,
    /** Bukkit sound name */ ENTITY_SKELETON_STEP("SKELETON_WALK"),
    /** Bukkit sound name */ ENTITY_SLIME_ATTACK("SLIME_ATTACK"),
    /** Bukkit sound name */ ENTITY_SLIME_DEATH,
    /** Bukkit sound name */ ENTITY_SLIME_DEATH_SMALL,
    /** Bukkit sound name */ ENTITY_SLIME_HURT,
    /** Bukkit sound name */ ENTITY_SLIME_HURT_SMALL("ENTITY_SMALL_SLIME_HURT"),
    /** Bukkit sound name */ ENTITY_SLIME_JUMP("SLIME_WALK"),
    /** Bukkit sound name */ ENTITY_SLIME_JUMP_SMALL("SLIME_WALK2", "ENTITY_SMALL_SLIME_SQUISH"),
    /** Bukkit sound name */ ENTITY_SLIME_SQUISH("SLIME_WALK2"),
    /** Bukkit sound name */ ENTITY_SLIME_SQUISH_SMALL("ENTITY_SMALL_SLIME_SQUISH"),
    /** Bukkit sound name */ ENTITY_SNOWBALL_THROW,
    /** Bukkit sound name */ ENTITY_SNOW_GOLEM_AMBIENT("ENTITY_SNOWMAN_AMBIENT"),
    /** Bukkit sound name */ ENTITY_SNOW_GOLEM_DEATH("ENTITY_SNOWMAN_DEATH"),
    /** Bukkit sound name */ ENTITY_SNOW_GOLEM_HURT("ENTITY_SNOWMAN_HURT"),
    /** Bukkit sound name */ ENTITY_SNOW_GOLEM_SHOOT("ENTITY_SNOWMAN_SHOOT"),
    /** Bukkit sound name */ ENTITY_SPIDER_AMBIENT("SPIDER_IDLE"),
    /** Bukkit sound name */ ENTITY_SPIDER_DEATH("SPIDER_DEATH"),
    /** Bukkit sound name */ ENTITY_SPIDER_HURT,
    /** Bukkit sound name */ ENTITY_SPIDER_STEP("SPIDER_WALK"),
    /** Bukkit sound name */ ENTITY_SPLASH_POTION_BREAK,
    /** Bukkit sound name */ ENTITY_SPLASH_POTION_THROW,
    /** Bukkit sound name */ ENTITY_SQUID_AMBIENT,
    /** Bukkit sound name */ ENTITY_SQUID_DEATH,
    /** Bukkit sound name */ ENTITY_SQUID_HURT,
    /** Bukkit sound name */ ENTITY_SQUID_SQUIRT,
    /** Bukkit sound name */ ENTITY_STRAY_AMBIENT,
    /** Bukkit sound name */ ENTITY_STRAY_DEATH,
    /** Bukkit sound name */ ENTITY_STRAY_HURT,
    /** Bukkit sound name */ ENTITY_STRAY_STEP,
    /** Bukkit sound name */ ENTITY_TNT_PRIMED("FUSE"),
    /** Bukkit sound name */ ENTITY_TROPICAL_FISH_AMBIENT,
    /** Bukkit sound name */ ENTITY_TROPICAL_FISH_DEATH,
    /** Bukkit sound name */ ENTITY_TROPICAL_FISH_FLOP("ENTITY_TROPICAL_FISH_DEATH"),
    /** Bukkit sound name */ ENTITY_TROPICAL_FISH_HURT,
    /** Bukkit sound name */ ENTITY_TURTLE_AMBIENT_LAND,
    /** Bukkit sound name */ ENTITY_TURTLE_DEATH,
    /** Bukkit sound name */ ENTITY_TURTLE_DEATH_BABY,
    /** Bukkit sound name */ ENTITY_TURTLE_EGG_BREAK,
    /** Bukkit sound name */ ENTITY_TURTLE_EGG_CRACK,
    /** Bukkit sound name */ ENTITY_TURTLE_EGG_HATCH,
    /** Bukkit sound name */ ENTITY_TURTLE_HURT,
    /** Bukkit sound name */ ENTITY_TURTLE_HURT_BABY,
    /** Bukkit sound name */ ENTITY_TURTLE_LAY_EGG,
    /** Bukkit sound name */ ENTITY_TURTLE_SHAMBLE,
    /** Bukkit sound name */ ENTITY_TURTLE_SHAMBLE_BABY,
    /** Bukkit sound name */ ENTITY_TURTLE_SWIM,
    /** Bukkit sound name */ ENTITY_VEX_AMBIENT,
    /** Bukkit sound name */ ENTITY_VEX_CHARGE,
    /** Bukkit sound name */ ENTITY_VEX_DEATH,
    /** Bukkit sound name */ ENTITY_VEX_HURT,
    /** Bukkit sound name */ ENTITY_VILLAGER_AMBIENT("VILLAGER_IDLE"),
    /** Bukkit sound name */ ENTITY_VILLAGER_CELEBRATE,
    /** Bukkit sound name */ ENTITY_VILLAGER_DEATH("VILLAGER_DEATH"),
    /** Bukkit sound name */ ENTITY_VILLAGER_HURT("VILLAGER_HIT"),
    /** Bukkit sound name */ ENTITY_VILLAGER_NO("VILLAGER_NO"),
    /** Bukkit sound name */ ENTITY_VILLAGER_TRADE("VILLAGER_HAGGLE", "ENTITY_VILLAGER_TRADING"),
    /** Bukkit sound name */ ENTITY_VILLAGER_WORK_ARMORER,
    /** Bukkit sound name */ ENTITY_VILLAGER_WORK_BUTCHER,
    /** Bukkit sound name */ ENTITY_VILLAGER_WORK_CARTOGRAPHER,
    /** Bukkit sound name */ ENTITY_VILLAGER_WORK_CLERIC,
    /** Bukkit sound name */ ENTITY_VILLAGER_WORK_FARMER,
    /** Bukkit sound name */ ENTITY_VILLAGER_WORK_FISHERMAN,
    /** Bukkit sound name */ ENTITY_VILLAGER_WORK_FLETCHER,
    /** Bukkit sound name */ ENTITY_VILLAGER_WORK_LEATHERWORKER,
    /** Bukkit sound name */ ENTITY_VILLAGER_WORK_LIBRARIAN,
    /** Bukkit sound name */ ENTITY_VILLAGER_WORK_MASON,
    /** Bukkit sound name */ ENTITY_VILLAGER_WORK_SHEPHERD,
    /** Bukkit sound name */ ENTITY_VILLAGER_WORK_TOOLSMITH,
    /** Bukkit sound name */ ENTITY_VILLAGER_WORK_WEAPONSMITH,
    /** Bukkit sound name */ ENTITY_VILLAGER_YES("VILLAGER_YES"),
    /** Bukkit sound name */ ENTITY_VINDICATOR_AMBIENT("ENTITY_VINDICATION_ILLAGER_AMBIENT"),
    /** Bukkit sound name */ ENTITY_VINDICATOR_CELEBRATE,
    /** Bukkit sound name */ ENTITY_VINDICATOR_DEATH("ENTITY_VINDICATION_ILLAGER_DEATH"),
    /** Bukkit sound name */ ENTITY_VINDICATOR_HURT("ENTITY_VINDICATION_ILLAGER_HURT"),
    /** Bukkit sound name */ ENTITY_WANDERING_TRADER_AMBIENT,
    /** Bukkit sound name */ ENTITY_WANDERING_TRADER_DEATH,
    /** Bukkit sound name */ ENTITY_WANDERING_TRADER_DISAPPEARED,
    /** Bukkit sound name */ ENTITY_WANDERING_TRADER_DRINK_MILK,
    /** Bukkit sound name */ ENTITY_WANDERING_TRADER_DRINK_POTION,
    /** Bukkit sound name */ ENTITY_WANDERING_TRADER_HURT,
    /** Bukkit sound name */ ENTITY_WANDERING_TRADER_NO,
    /** Bukkit sound name */ ENTITY_WANDERING_TRADER_REAPPEARED,
    /** Bukkit sound name */ ENTITY_WANDERING_TRADER_TRADE,
    /** Bukkit sound name */ ENTITY_WANDERING_TRADER_YES,
    /** Bukkit sound name */ ENTITY_WITCH_AMBIENT,
    /** Bukkit sound name */ ENTITY_WITCH_CELEBRATE,
    /** Bukkit sound name */ ENTITY_WITCH_DEATH,
    /** Bukkit sound name */ ENTITY_WITCH_DRINK,
    /** Bukkit sound name */ ENTITY_WITCH_HURT,
    /** Bukkit sound name */ ENTITY_WITCH_THROW,
    /** Bukkit sound name */ ENTITY_WITHER_AMBIENT("WITHER_IDLE"),
    /** Bukkit sound name */ ENTITY_WITHER_BREAK_BLOCK,
    /** Bukkit sound name */ ENTITY_WITHER_DEATH("WITHER_DEATH"),
    /** Bukkit sound name */ ENTITY_WITHER_HURT("WITHER_HURT"),
    /** Bukkit sound name */ ENTITY_WITHER_SHOOT("WITHER_SHOOT"),
    /** Bukkit sound name */ ENTITY_WITHER_SKELETON_AMBIENT,
    /** Bukkit sound name */ ENTITY_WITHER_SKELETON_DEATH,
    /** Bukkit sound name */ ENTITY_WITHER_SKELETON_HURT,
    /** Bukkit sound name */ ENTITY_WITHER_SKELETON_STEP,
    /** Bukkit sound name */ ENTITY_WITHER_SPAWN("WITHER_SPAWN"),
    /** Bukkit sound name */ ENTITY_WOLF_AMBIENT("WOLF_BARK"),
    /** Bukkit sound name */ ENTITY_WOLF_DEATH("WOLF_DEATH"),
    /** Bukkit sound name */ ENTITY_WOLF_GROWL("WOLF_GROWL"),
    /** Bukkit sound name */ ENTITY_WOLF_HOWL("WOLF_HOWL"),
    /** Bukkit sound name */ ENTITY_WOLF_HURT("WOLF_HURT"),
    /** Bukkit sound name */ ENTITY_WOLF_PANT("WOLF_PANT"),
    /** Bukkit sound name */ ENTITY_WOLF_SHAKE("WOLF_SHAKE"),
    /** Bukkit sound name */ ENTITY_WOLF_STEP("WOLF_WALK"),
    /** Bukkit sound name */ ENTITY_WOLF_WHINE("WOLF_WHINE"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_AMBIENT("ZOMBIE_IDLE"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_ATTACK_IRON_DOOR("ZOMBIE_METAL"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR("ZOMBIE_WOOD", "ENTITY_ZOMBIE_ATTACK_DOOR_WOOD"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_BREAK_WOODEN_DOOR("ZOMBIE_WOODBREAK", "ENTITY_ZOMBIE_BREAK_DOOR_WOOD"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_CONVERTED_TO_DROWNED,
    /** Bukkit sound name */ ENTITY_ZOMBIE_DEATH("ZOMBIE_DEATH"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_DESTROY_EGG,
    /** Bukkit sound name */ ENTITY_ZOMBIE_HORSE_AMBIENT("HORSE_ZOMBIE_IDLE"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_HORSE_DEATH("HORSE_ZOMBIE_DEATH"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_HORSE_HURT("HORSE_ZOMBIE_HIT"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_HURT("ZOMBIE_HURT"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_INFECT("ZOMBIE_INFECT"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_PIGMAN_AMBIENT("ZOMBIE_PIG_IDLE", "ENTITY_ZOMBIE_PIG_AMBIENT"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_PIGMAN_ANGRY("ZOMBIE_PIG_ANGRY", "ENTITY_ZOMBIE_PIG_ANGRY"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_PIGMAN_DEATH("ZOMBIE_PIG_DEATH", "ENTITY_ZOMBIE_PIG_DEATH"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_PIGMAN_HURT("ZOMBIE_PIG_HURT", "ENTITY_ZOMBIE_PIG_HURT"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_STEP("ZOMBIE_WALK"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_VILLAGER_AMBIENT,
    /** Bukkit sound name */ ENTITY_ZOMBIE_VILLAGER_CONVERTED("ZOMBIE_UNFECT"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_VILLAGER_CURE("ZOMBIE_REMEDY"),
    /** Bukkit sound name */ ENTITY_ZOMBIE_VILLAGER_DEATH,
    /** Bukkit sound name */ ENTITY_ZOMBIE_VILLAGER_HURT,
    /** Bukkit sound name */ ENTITY_ZOMBIE_VILLAGER_STEP,
    /** Bukkit sound name */ EVENT_RAID_HORN,
    /** Bukkit sound name */ ITEM_ARMOR_EQUIP_CHAIN,
    /** Bukkit sound name */ ITEM_ARMOR_EQUIP_DIAMOND,
    /** Bukkit sound name */ ITEM_ARMOR_EQUIP_ELYTRA,
    /** Bukkit sound name */ ITEM_ARMOR_EQUIP_GENERIC,
    /** Bukkit sound name */ ITEM_ARMOR_EQUIP_GOLD,
    /** Bukkit sound name */ ITEM_ARMOR_EQUIP_IRON,
    /** Bukkit sound name */ ITEM_ARMOR_EQUIP_LEATHER,
    /** Bukkit sound name */ ITEM_ARMOR_EQUIP_TURTLE,
    /** Bukkit sound name */ ITEM_AXE_STRIP,
    /** Bukkit sound name */ ITEM_BOOK_PAGE_TURN,
    /** Bukkit sound name */ ITEM_BOOK_PUT,
    /** Bukkit sound name */ ITEM_BOTTLE_EMPTY,
    /** Bukkit sound name */ ITEM_BOTTLE_FILL,
    /** Bukkit sound name */ ITEM_BOTTLE_FILL_DRAGONBREATH,
    /** Bukkit sound name */ ITEM_BUCKET_EMPTY,
    /** Bukkit sound name */ ITEM_BUCKET_EMPTY_FISH,
    /** Bukkit sound name */ ITEM_BUCKET_EMPTY_LAVA,
    /** Bukkit sound name */ ITEM_BUCKET_FILL,
    /** Bukkit sound name */ ITEM_BUCKET_FILL_FISH,
    /** Bukkit sound name */ ITEM_BUCKET_FILL_LAVA,
    /** Bukkit sound name */ ITEM_CHORUS_FRUIT_TELEPORT,
    /** Bukkit sound name */ ITEM_CROP_PLANT,
    /** Bukkit sound name */ ITEM_CROSSBOW_HIT,
    /** Bukkit sound name */ ITEM_CROSSBOW_LOADING_END,
    /** Bukkit sound name */ ITEM_CROSSBOW_LOADING_MIDDLE,
    /** Bukkit sound name */ ITEM_CROSSBOW_LOADING_START,
    /** Bukkit sound name */ ITEM_CROSSBOW_QUICK_CHARGE_1,
    /** Bukkit sound name */ ITEM_CROSSBOW_QUICK_CHARGE_2,
    /** Bukkit sound name */ ITEM_CROSSBOW_QUICK_CHARGE_3,
    /** Bukkit sound name */ ITEM_CROSSBOW_SHOOT,
    /** Bukkit sound name */ ITEM_ELYTRA_FLYING,
    /** Bukkit sound name */ ITEM_FIRECHARGE_USE,
    /** Bukkit sound name */ ITEM_FLINTANDSTEEL_USE("FIRE_IGNITE"),
    /** Bukkit sound name */ ITEM_HOE_TILL,
    /** Bukkit sound name */ ITEM_HONEY_BOTTLE_DRINK,
    /** Bukkit sound name */ ITEM_NETHER_WART_PLANT,
    /** Bukkit sound name */ ITEM_SHIELD_BLOCK,
    /** Bukkit sound name */ ITEM_SHIELD_BREAK,
    /** Bukkit sound name */ ITEM_SHOVEL_FLATTEN,
    /** Bukkit sound name */ ITEM_SWEET_BERRIES_PICK_FROM_BUSH,
    /** Bukkit sound name */ ITEM_TOTEM_USE,
    /** Bukkit sound name */ ITEM_TRIDENT_HIT,
    /** Bukkit sound name */ ITEM_TRIDENT_HIT_GROUND,
    /** Bukkit sound name */ ITEM_TRIDENT_RETURN,
    /** Bukkit sound name */ ITEM_TRIDENT_RIPTIDE_1,
    /** Bukkit sound name */ ITEM_TRIDENT_RIPTIDE_2("ITEM_TRIDENT_RIPTIDE_1"),
    /** Bukkit sound name */ ITEM_TRIDENT_RIPTIDE_3("ITEM_TRIDENT_RIPTIDE_1"),
    /** Bukkit sound name */ ITEM_TRIDENT_THROW,
    /** Bukkit sound name */ ITEM_TRIDENT_THUNDER,
    /** Bukkit sound name */ MUSIC_CREATIVE,
    /** Bukkit sound name */ MUSIC_CREDITS,
    /** Bukkit sound name */ MUSIC_DISC_11("RECORD_11"),
    /** Bukkit sound name */ MUSIC_DISC_13("RECORD_13"),
    /** Bukkit sound name */ MUSIC_DISC_BLOCKS("RECORD_BLOCKS"),
    /** Bukkit sound name */ MUSIC_DISC_CAT("RECORD_CAT"),
    /** Bukkit sound name */ MUSIC_DISC_CHIRP("RECORD_CHIRP"),
    /** Bukkit sound name */ MUSIC_DISC_FAR("RECORD_FAR"),
    /** Bukkit sound name */ MUSIC_DISC_MALL("RECORD_MALL"),
    /** Bukkit sound name */ MUSIC_DISC_MELLOHI("RECORD_MELLOHI"),
    /** Bukkit sound name */ MUSIC_DISC_STAL("RECORD_STAL"),
    /** Bukkit sound name */ MUSIC_DISC_STRAD("RECORD_STRAD"),
    /** Bukkit sound name */ MUSIC_DISC_WAIT("RECORD_WAIT"),
    /** Bukkit sound name */ MUSIC_DISC_WARD("RECORD_WARD"),
    /** Bukkit sound name */ MUSIC_DRAGON,
    /** Bukkit sound name */ MUSIC_END,
    /** Bukkit sound name */ MUSIC_GAME,
    /** Bukkit sound name */ MUSIC_MENU,
    /** Bukkit sound name */ MUSIC_NETHER,
    /** Bukkit sound name */ MUSIC_UNDER_WATER,
    /** Bukkit sound name */ UI_BUTTON_CLICK("CLICK"),
    /** Bukkit sound name */ UI_CARTOGRAPHY_TABLE_TAKE_RESULT,
    /** Bukkit sound name */ UI_LOOM_SELECT_PATTERN,
    /** Bukkit sound name */ UI_LOOM_TAKE_RESULT,
    /** Bukkit sound name */ UI_STONECUTTER_SELECT_RECIPE,
    /** Bukkit sound name */ UI_STONECUTTER_TAKE_RESULT,
    /** Bukkit sound name */ UI_TOAST_CHALLENGE_COMPLETE,
    /** Bukkit sound name */ UI_TOAST_IN,
    /** Bukkit sound name */ UI_TOAST_OUT,
    /** Bukkit sound name */ WEATHER_RAIN("AMBIENCE_RAIN"),
    /** Bukkit sound name */ WEATHER_RAIN_ABOVE;

    /** Reflection sound format patter */
    protected static final Pattern FORMAT_PATTERN = Pattern.compile("\\d+|\\W+");

    /** Bukkit sound legacy name array */
    protected final String[] legacy;

    /**
     * What this does is to save the sound in cache
     * since this KarmaSound doesn't has a method like
     * org.bukkit.Material.getMaterial();
     */
    protected final Cache<Sound, com.google.common.base.Optional<org.bukkit.Sound>> CACHE = CacheBuilder.newBuilder()
            .expireAfterAccess(10, TimeUnit.MINUTES)
            .softValues()
            .build();

    /**
     * Initialize the sounds and legacy
     * ones so can be reflected
     *
     * @param legacy the legacy sounds
     */
    Sound(String... legacy) {
        this.legacy = legacy;
    }

    /**
     * This will try to format the string like
     * an enum value
     *
     * @param name the enum name
     * @return a String
     */
    protected final String format(String name) {
        return FORMAT_PATTERN.matcher(
                name.trim().replace('-', '_').replace(' ', '_')).replaceAll("").toUpperCase(Locale.ENGLISH);
    }

    /**
     * Transform the KarmaSound into a Bukkit sound
     * so it can be played
     *
     * @return a Sound
     */
    @SuppressWarnings({"Guava", "OptionalAssignedToNull"})
    protected final org.bukkit.Sound parseSound() {
        com.google.common.base.Optional<org.bukkit.Sound> cachedSound = CACHE.getIfPresent(this);
        if (cachedSound != null) return cachedSound.orNull();
        com.google.common.base.Optional<org.bukkit.Sound> sound;

        sound = Enums.getIfPresent(org.bukkit.Sound.class, this.name());

        if (!sound.isPresent()) {
            for (String legacy : this.legacy) {
                sound = Enums.getIfPresent(org.bukkit.Sound.class, legacy);
                if (sound.isPresent()) break;
            }
        }

        CACHE.put(this, sound);
        return sound.orNull();
    }
}
